### ISSUE TITLE
scarlink_tiles: Unable to synchronously open object (component not found)

### ISSUE THREAD

**Issue by ofircohn** [snehamitra/SCARlink#10]
Hey! 
Thank you for this great tool!!
Need some help :) 

scarlink_tiles -o outdir2 -c group

Traceback (most recent call last):
  File "scarlink_tiles", line 33, in <module>
    sys.exit(load_entry_point('scarlink', 'console_scripts', 'scarlink_tiles')())
  File "run_scarlink_tiles.py", line 28, in main
    df = rm.get_gene_tile_significance(gene, celltype_col)
  File "model.py", line 296, in get_gene_tile_significance
    m_z = read_sparse_significance(f, k, 'z-score')
  File "read_h5_and_group_cells.py", line 197, in read_sparse_significance
    g = f[k + '/' + entry]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to synchronously open object (component not found)'

Thank you!

**Comment by snehamitra** [comment]
Seems like there is no entry for `group` in the file. Were you able to run `scarlink ... -c group` before `scarlink_tiles` without any errors?

**Comment by ofircohn** [comment]
Yes, no errors.
I can also generate plots (e.g, scv.get_scarlink_output)

**Comment by snehamitra** [comment]
The error looks like a key is missing in the output file. Could you check the following:

```python
import h5py
import glob
filenames = glob.glob("outdir2/scarlink_out/*.hd5")
for filename in filenames:
       print(filename)
       f = h5py.File(filename, 'r')
       print([f['tile_significance/group/' + g].keys() for g in f['tile_significance/group'].keys()])
       f.close()
```

**Comment by ofircohn** [comment]
Hey!
(1) It seems that 3 of 100 hd5 files missing keys.
Usually: Group: /genes/  Group: /tile_significance/ and Group: /tile_significance/group/
However, these 3 have only Group: /genes/.

(2) I inspected one of these files:
(a) Group: /genes/
Dataset: /genes/ACER3, shape: (1333, 1), dtype: float32
..
...
(b) The log file looks good:
2024-06-28 20:58:23 INFO     Training regression model on ACER3
2024-06-28 20:58:23 INFO     Performing 5-fold cross validation...
2024-06-28 21:13:06 INFO     Avg. cross-validation spearman correlation: 0.32664258158115667

(c) And generates the plot file:
scv.plot_scarlink_output(scarlink_out, genes=['ACER3'], celltype='group', figsize=(7, 7))

**Comment by ofircohn** [comment]
Hey! I re-run them (all files with <KeysViewHDF5 ['p-value', 'z-score']>]), but still having issues.

Traceback (most recent call last):
  File "scarlink_tiles", line 33, in <module>
    sys.exit(load_entry_point('scarlink', 'console_scripts', 'scarlink_tiles')())
  File "run_scarlink_tiles.py", line 28, in main
    df = rm.get_gene_tile_significance(gene, celltype_col)
  File "model.py", line 296, in get_gene_tile_significance
    m_z = read_sparse_significance(f, k, 'z-score')
  File "read_h5_and_group_cells.py", line 197, in read_sparse_significance
    g = f[k + '/' + entry]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to synchronously open object (component not found)'

**Comment by snehamitra** [comment]
`scarlink_tiles` generates the 'p-value' and 'z-score' entries in the hd5 files. Did you run `scarlink_tiles` on the 3 runs that did not have these entries?
