### ISSUE TITLE
Problem running scarlink_processing on pbmc test data

### ISSUE THREAD

**Issue by JaBa90** [snehamitra/SCARlink#13]
Hi,

After installing SCARlink without issue, I am facing an issue with the first command of the exemplary data.

I run the command in the scarlink conda env:

scarlink_processing --scrna /path/pbmc_test_input/pbmc_scrna_test.rds --scatac /path/pbmc_test_input/pbmc_scatac_test -o /path/pbmc_test_input/multiome_out -nc 16

With the following issue:

[1] "9460 cells in common between scATAC and scRNA objects"
R[write to console]: ArchR logging to : ArchRLogs/ArchR-getMatrixFromProject-65102a5b011b-Date-2024-07-11_Time-16-50-02.log
If there is an issue, please report to github with logFile!

R[write to console]: 2024-07-11 16:50:17 : Organizing colData, 0.248 mins elapsed.

R[write to console]: 2024-07-11 16:50:17 : Organizing rowData, 0.248 mins elapsed.

R[write to console]: 2024-07-11 16:50:17 : Organizing rowRanges, 0.248 mins elapsed.

R[write to console]: 2024-07-11 16:50:17 : Organizing Assays (1 of 1), 0.248 mins elapsed.

R[write to console]: 2024-07-11 16:50:17 : Constructing SummarizedExperiment, 0.248 mins elapsed.

R[write to console]: 2024-07-11 16:50:18 : Finished Matrix Creation, 0.257 mins elapsed.

[1] "Tile size: 500"
R[write to console]: Error in H5Ocopy(fid2, gene, h5loc_dest = fid, name_dest = gene) : 
  could not find function "H5Ocopy"

R[write to console]: In addition: 
R[write to console]: Warning messages:

R[write to console]: 1: package ‘Matrix’ was built under R version 4.1.3 

R[write to console]: 2: package ‘Seurat’ was built under R version 4.1.3 

R[write to console]: 3: 
R[write to console]: In valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE) :
R[write to console]: 
 
R[write to console]:  GRanges object contains 38 out-of-bound ranges located on sequences
  chr1, chr3, chr4, chr5, chr7, chr8, chr9, chr10, chr11, chr12, chr16,
  chr17, chr18, chr19, and chr20. Note that ranges located on a sequence
  whose length is unknown (NA) or on a circular sequence are not
  considered out-of-bound (use seqlengths() and isCircular() to get the
  lengths and circularity flags of the underlying sequences). You can use
  trim() to trim these ranges. See ?`trim,GenomicRanges-method` for more
  information.

R[write to console]: 4: 
R[write to console]: In valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE) :
R[write to console]: 
 
R[write to console]:  GRanges object contains 87 out-of-bound ranges located on sequences
  chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11,
  chr12, chr13, chr15, chr16, chr17, chr18, chr19, chr20, chr21, and
  chr22. Note that ranges located on a sequence whose length is unknown
  (NA) or on a circular sequence are not considered out-of-bound (use
  seqlengths() and isCircular() to get the lengths and circularity flags
  of the underlying sequences). You can use trim() to trim these ranges.
  See ?`trim,GenomicRanges-method` for more information.

R[write to console]: 5: 
R[write to console]: In valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE) :
R[write to console]: 
 
R[write to console]:  GRanges object contains 124 out-of-bound ranges located on sequences
  chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11,
  chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21,
  and chr22. Note that ranges located on a sequence whose length is
  unknown (NA) or on a circular sequence are not considered out-of-bound
  (use seqlengths() and isCircular() to get the lengths and circularity
  flags of the underlying sequences). You can use trim() to trim these
  ranges. See ?`trim,GenomicRanges-method` for more information.

R[write to console]: 6: 
R[write to console]: In valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE) :
R[write to console]: 
 
R[write to console]:  GRanges object contains 155 out-of-bound ranges located on sequences
  chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11,
  chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21,
  and chr22. Note that ranges located on a sequence whose length is
  unknown (NA) or on a circular sequence are not considered out-of-bound
  (use seqlengths() and isCircular() to get the lengths and circularity
  flags of the underlying sequences). You can use trim() to trim these
  ranges. See ?`trim,GenomicRanges-method` for more information.

Traceback (most recent call last):
  File "/path/miniconda3/envs/scarlink-env/bin/scarlink_processing", line 33, in <module>
    sys.exit(load_entry_point('scarlink', 'console_scripts', 'scarlink_processing')())
  File "/path/SCARlink/scarlink/preprocessing/create_h5_files.py", line 44, in main
    rfunc.write_files(archr_out, seurat_out, out_dir, args.window, args.ncores, args.scale)
  File "/path/miniconda3/envs/scarlink-env/lib/python3.8/site-packages/rpy2/robjects/functions.py", line 208, in __call__
    return (super(SignatureTranslatedFunction, self)
  File "/path/miniconda3/envs/scarlink-env/lib/python3.8/site-packages/rpy2/robjects/functions.py", line 131, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/path/miniconda3/envs/scarlink-env/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/path/miniconda3/envs/scarlink-env/lib/python3.8/site-packages/rpy2/rinterface.py", line 817, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in H5Ocopy(fid2, gene, h5loc_dest = fid, name_dest = gene) : 
  could not find function "H5Ocopy"

###############################################################################################

I tried many things like installing rhdf5 and h5py, but unfortunately, nothing worked out so far. I would really appreciate your help.

Thanks,
Jan

**Comment by hmummey** [comment]
I'm having this same problem and I think it's because the version of rhdf5 in my scarlink-env is too old. If you run `ls('package:rhdf5')` in R in your environment you can see that `H5Ocopy` isn't a function in the package. However, looking at all functions in the current version of rhdf5 [here](https://rdrr.io/github/grimbough/rhdf5/api/), you can find `H5Ocopy`. 

I had to pin older versions of Seurat, and GenomeInfoDbData when making my scarlink-env and so my rhdf5 is v2.38.1, but the most recent version is v2.48. Currently I haven't been able to find a way to upgrade rhdf5 though because my environment is R4.1. It would be really helpful if someone who has a fully working environment could post the versions of all packages installed in it.
