### ISSUE TITLE
Reproducing the results of fig3

### ISSUE THREAD

**Issue by fanyue322** [snehamitra/SCARlink#9]
Hi Authors,

I am trying to reproduce the results of Fig3,  I was able to run and finish almost all steps except
```
utils_GWAS.plot_enrichment_per_gene_linked_tiles_peaks([pbmc_ukbb_file], ukbb_file, sqtl_dir)
```
which reports the following error:
```
Cutoff: 2.5892340675066318e-18 4.2585941105310803e-110
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuef2/project/ATAC/MISAR-seq/GWAS_finemapping/scripts/utils_GWAS.py", line 240, in plot_enrichment_per_gene_linked_tiles_peaks
    df_cutoffs = calc_and_plot_enrichment_recall(merged_df, pip=0.2, n_link_cutoffs=n_link_cutoffs_hvg)
  File "/home/yuef2/project/ATAC/MISAR-seq/GWAS_finemapping/scripts/utils_GWAS.py", line 190, in calc_and_plot_enrichment_recall
    df_cutoff = get_bootstrapped_df(e_df)
  File "/home/yuef2/project/ATAC/MISAR-seq/GWAS_finemapping/scripts/utils_GWAS.py", line 162, in get_bootstrapped_df
    bootstrap_ci_s = scipy.stats.bootstrap((df[df['method']=='SCARlink'][['enrichment', 'recall', 'precision']].values,), lambda x: np.mean(x, axis=0), n_resamples=1000, confidence_level=0.95, random_state=9, method='basic') 
  File "/home/yuef2/miniconda3/envs/scarlink-env/lib/python3.8/site-packages/scipy/stats/_resampling.py", line 470, in bootstrap
    theta_hat_b.append(statistic(*resampled_data, axis=-1))
TypeError: <lambda>() got an unexpected keyword argument 'axis'
```
I have installed all packages as the tutorial, any clue about solving this issue?

Best regards.

**Comment by snehamitra** [comment]
Fig3 notebook requires `pyranges` and `pyarrow`. Were any of the installed packages updated while installing these two packages? Can you list the versions of all the installed packages?
